version: "3"

services:
  shopping:
    container_name: shop
    build:
      context: ../.
    ports:
      - "8080:8080"
    networks:
      - shopping
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    image: postgres:alpine
    container_name: shopping-postgres
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    networks:
      - shopping
networks:
  shopping:
    driver: bridge