#version: "3"
#
#services:
#  postgres:
#    image: postgres:alpine
#    container_name: postgres
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=postgres
#      - DB_URL=jdbc:postgresql://localhost:5432/shop