spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: Shopping
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  jpa:
    open-in-view: off
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: update
    database: postgresql
    show-sql: true
