spring:
  application:
    name: Shoping
  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/changelog-master.yaml
    enabled: true
